# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='NA', upload_to='templates'),
        ),
    ]
