# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20160503_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='/media/'),
        ),
    ]
